### ISSUE TITLE
Jibri - org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized

### ISSUE THREAD

**Issue by palmtown** [jitsi-contrib/jitsi-helm#74]
Hello Community,

When I installed the Helm Chart with no modifications besides required variables, Jibri will fail to record meetings.  After investigation, I found the error below was being generated on the jibri server.  I was able to solve the error by creating the jibri and record user manually on the prosody server.  Thereafter, I was able to record a meeting.

Therefore, there seems to be an issue when the users are created.  I was able to resolve by reading the post here: https://community.jitsi.org/t/jibri-saslerror-using-scram-sha-1-not-authorized/63146/3.

Anyone else experiencing this issue?  Is this a bug or is there a workaround?

Error
Jibri 2023-03-20 01:52:18.249 WARNING: [31] [hostname=jitsi-meet-prosody.default.svc.cluster.local id=jitsi-meet-prosody.default.svc.cluster.local] MucClient.lambda$getConnectAndLoginCallable$9#651: Failed to login. Disconnecting to trigger a re-connect.
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:286)
        at org.jivesoftware.smack.AbstractXMPPConnection.lambda$new$2(AbstractXMPPConnection.java:407)
        at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.accept(NonzaCallback.java:177)
        at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.access$200(NonzaCallback.java:166)
        at org.jivesoftware.smack.NonzaCallback.onNonzaReceived(NonzaCallback.java:46)
        at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessNonza(AbstractXMPPConnection.java:1444)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1700(XMPPTCPConnection.java:131)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1010)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by palmtown** [comment]
One issue I found which is that I needed to uncomment the below settings in values.yaml.  It is not mentioned in the [README.md](https://github.com/jitsi-contrib/jitsi-helm#readme), and I found it when investigating the entire values.yaml file.  Maybe good a good idea to add instructions to the [README.md](https://github.com/jitsi-contrib/jitsi-helm#readme).    I can submit a PR if it helps.

## Uncomment this if you want to use jibri:
  # - secretRef:
  #     name: '{{ include "prosody.fullname" . }}-jibri'

**Comment by spijet** [comment]
Hello @palmtown!

Sorry for the late answer. Yes, it's necessary to uncomment this part in `values.yaml`, so that Prosody knows about Jibri and registers it in its' own internal user database.

I'll add this to the README soon, thank you.

**Comment by spijet** [comment]
Fixed in 0b952897 (and release v1.3.4).
